"""Modulo identity - capa de identidad del framework 3 niveles (FA-2).

FA-2.1: temporal_filter.py (filtro canonico por PERIODOFREPORT).
FA-2.2: cusip_resolver.py (CUSIP -> ticker con vigencia temporal).
FA-2.3: relationships.py (Column 7 -> OTHERMANAGER2.SEQUENCENUMBER).
FA-2.4: amendments.py (canonical snapshot composicional).
NIPC:  sec13f_list.py (SEC Official List 13(f) parser fixed-width 80).
NIPC:  security_identity.py (C1-revisada: canonical_security).

Fuera de FA-2.4: NIPC, breadth, clasificacion, cross-validation N-PORT
(post Gate FA-2).
"""

from .amendments import (
    ALL_ANOMALIES,
    ALL_STATUSES,
    ALL_STRATEGIES,
    ANOMALY_AMBIGUOUS_BASE,
    ANOMALY_AMBIGUOUS_ORDER,
    ANOMALY_HR_WITH_AMENDMENT_FLAGS,
    ANOMALY_NT_AUGMENTED,
    ANOMALY_REVIEW_REQUIRED,
    OP_ADD,
    OP_NO_HOLDINGS,
    OP_REPLACE,
    STATUS_CANONICAL,
    STATUS_CANONICAL_COMPOSITE,
    STATUS_NO_HOLDINGS,
    STATUS_REVIEW_REQUIRED,
    STATUS_SOURCE_ANOMALY,
    STRATEGY_HR_CHAIN_RESTATEMENT,
    STRATEGY_HR_COMPOSITE,
    STRATEGY_HR_PLUS_NEW_HOLDINGS,
    STRATEGY_HR_PLUS_RESTATEMENT,
    STRATEGY_NOTICE_AMENDED,
    STRATEGY_REVIEW_REQUIRED,
    STRATEGY_SINGLE_HR,
    STRATEGY_SINGLE_NOTICE,
    apply_amendments,
    classify_strategy,
    compute_status_counts,
    compute_strategy_counts,
    detect_base_filing,
    order_filings,
)
from .cusip_resolver import (
    DEFAULT_EXCEPTIONS_PATH,
    FORBIDDEN_SOURCES,
    REQUIRED_COLUMNS,
    VALID_VERIFIED_BY,
    load_exceptions,
    resolve_batch,
    resolve_cusip,
)
from .relationships import (
    CANONICAL_KEY_COLUMNS,
    EDGE_COLUMNS,
    FORBIDDEN_TERMS,
    PROVISIONAL_FLAG,
    SEQ_MAX_DOMAIN,
    STATUS_INVALID_NONNUMERIC,
    STATUS_INVALID_OUT_OF_DOMAIN,
    STATUS_INVALID_ZERO,
    STATUS_NO_REFERENCE,
    STATUS_RESOLVED,
    STATUS_UNMAPPED_MISSING_OM2,
    build_canonical_relationship,
    build_filing_manager_index,
    build_om2_seq_index,
    build_provenance_index,
    check_edge_uniqueness,
    classify_token,
    compute_edge_metrics,
    compute_source_line_count,
    explode_othermanager_edges,
)
from .temporal_filter import CANONICAL_PERIOD_FIELD, FULL_PERIOD, filter_by_period
from .sec13f_list import (
    ALL_STATUSES as SEC13F_LIST_STATUSES,
    COLUMNS as SEC13F_LIST_COLUMNS,
    ELIGIBLE_STATES as SEC13F_LIST_ELIGIBLE_STATES,
    LINE_WIDTH as SEC13F_LIST_LINE_WIDTH,
    STATUS_ACTIVE as SEC13F_LIST_STATUS_ACTIVE,
    STATUS_ADDED as SEC13F_LIST_STATUS_ADDED,
    STATUS_CONFLICT as SEC13F_LIST_STATUS_CONFLICT,
    STATUS_DELETED as SEC13F_LIST_STATUS_DELETED,
    STATUS_NOT_IN_LIST as SEC13F_LIST_STATUS_NOT_IN_LIST,
    compute_eligibility_coverage,
    load_official_list,
    parse_line,
    parse_official_list_text,
    resolve_eligibility,
)
from .security_identity import (
    ALL_KINDS as SI_ALL_KINDS,
    ALL_STATUSES as SI_ALL_STATUSES,
    DEFAULT_EQUIVALENCE_PATH,
    EQUIVALENCE_COLUMNS,
    KIND_CANONICAL_EQUIVALENCE as SI_KIND_CANONICAL_EQUIVALENCE,
    KIND_CANONICAL_FIGI as SI_KIND_CANONICAL_FIGI,
    KIND_OBSERVED_CUSIP_ONLY as SI_KIND_OBSERVED_CUSIP_ONLY,
    KIND_UNRESOLVED as SI_KIND_UNRESOLVED,
    STATUS_AMBIGUOUS as SI_STATUS_AMBIGUOUS,
    STATUS_CANONICAL as SI_STATUS_CANONICAL,
    STATUS_CONFLICT as SI_STATUS_CONFLICT,
    STATUS_OBSERVED_ONLY as SI_STATUS_OBSERVED_ONLY,
    STATUS_UNRESOLVED as SI_STATUS_UNRESOLVED,
    compute_identity_coverage,
    load_crosswalk_internal,
    load_cusip_equivalence,
    observed_security_key,
    resolve_batch_identities,
    resolve_security_identity,
)

__all__ = [
    "filter_by_period", "CANONICAL_PERIOD_FIELD", "FULL_PERIOD",
    "load_official_list", "parse_official_list_text", "parse_line",
    "resolve_eligibility", "compute_eligibility_coverage",
    "SEC13F_LIST_STATUSES", "SEC13F_LIST_COLUMNS",
    "SEC13F_LIST_ELIGIBLE_STATES", "SEC13F_LIST_LINE_WIDTH",
    "SEC13F_LIST_STATUS_ACTIVE", "SEC13F_LIST_STATUS_ADDED",
    "SEC13F_LIST_STATUS_CONFLICT", "SEC13F_LIST_STATUS_DELETED",
    "SEC13F_LIST_STATUS_NOT_IN_LIST",
    "resolve_security_identity", "resolve_batch_identities",
    "compute_identity_coverage", "observed_security_key",
    "load_cusip_equivalence", "load_crosswalk_internal",
    "EQUIVALENCE_COLUMNS", "DEFAULT_EQUIVALENCE_PATH",
    "SI_ALL_STATUSES", "SI_ALL_KINDS",
    "SI_STATUS_CANONICAL", "SI_STATUS_OBSERVED_ONLY", "SI_STATUS_UNRESOLVED",
    "SI_STATUS_AMBIGUOUS", "SI_STATUS_CONFLICT",
    "SI_KIND_CANONICAL_FIGI", "SI_KIND_CANONICAL_EQUIVALENCE",
    "SI_KIND_OBSERVED_CUSIP_ONLY", "SI_KIND_UNRESOLVED",
    "load_exceptions", "resolve_cusip", "resolve_batch",
    "REQUIRED_COLUMNS", "FORBIDDEN_SOURCES", "VALID_VERIFIED_BY",
    "DEFAULT_EXCEPTIONS_PATH",
    "classify_token", "explode_othermanager_edges",
    "build_canonical_relationship",
    "build_filing_manager_index", "build_om2_seq_index",
    "build_provenance_index",
    "compute_edge_metrics", "check_edge_uniqueness",
    "compute_source_line_count",
    "CANONICAL_KEY_COLUMNS", "EDGE_COLUMNS",
    "FORBIDDEN_TERMS", "PROVISIONAL_FLAG", "SEQ_MAX_DOMAIN",
    "STATUS_RESOLVED", "STATUS_NO_REFERENCE",
    "STATUS_INVALID_ZERO", "STATUS_INVALID_NONNUMERIC",
    "STATUS_INVALID_OUT_OF_DOMAIN", "STATUS_UNMAPPED_MISSING_OM2",
    "order_filings", "classify_strategy", "detect_base_filing",
    "apply_amendments", "compute_strategy_counts", "compute_status_counts",
    "ALL_STRATEGIES", "ALL_STATUSES", "ALL_ANOMALIES",
    "STRATEGY_SINGLE_HR", "STRATEGY_SINGLE_NOTICE",
    "STRATEGY_HR_PLUS_RESTATEMENT", "STRATEGY_HR_PLUS_NEW_HOLDINGS",
    "STRATEGY_HR_CHAIN_RESTATEMENT", "STRATEGY_HR_COMPOSITE",
    "STRATEGY_NOTICE_AMENDED", "STRATEGY_REVIEW_REQUIRED",
    "STATUS_CANONICAL", "STATUS_CANONICAL_COMPOSITE",
    "STATUS_NO_HOLDINGS", "STATUS_SOURCE_ANOMALY", "STATUS_REVIEW_REQUIRED",
    "ANOMALY_NT_AUGMENTED", "ANOMALY_HR_WITH_AMENDMENT_FLAGS",
    "ANOMALY_AMBIGUOUS_ORDER", "ANOMALY_AMBIGUOUS_BASE",
    "ANOMALY_REVIEW_REQUIRED",
    "OP_REPLACE", "OP_ADD", "OP_NO_HOLDINGS",
]
