"""
Registro de instrumentos canónicos con símbolos por proveedor.
El ticker canónico interno coincide con el de Yahoo Finance.
"""
# Registro de instrumentos con diferencias de símbolos entre proveedores.
INSTRUMENTS = {
    "BRK-B": {
        "yahoo": "BRK-B",
        "polygon": "BRK.B",
        "tiingo": "BRK.B",
        "alpha_vantage": "BRK.B",
        "finnhub": "BRK.B",
        "fmp": "BRK.B",
        "twelve_data": "BRK.B",
    },
    "BF-B": {
        "yahoo": "BF-B",
        "polygon": "BF.B",
        "tiingo": "BF.B",
        "alpha_vantage": "BF.B",
        "finnhub": "BF.B",
        "fmp": "BF.B",
        "twelve_data": "BF.B",
    },
    "MOGA": {
        "yahoo": "MOGA",
        "polygon": "MOGA",
        "tiingo": "MOGA",
        "alpha_vantage": "MOGA",
        "finnhub": "MOGA",
        "fmp": "MOGA",
        "twelve_data": "MOGA",
        "note": "Yahoo falla con MOGA, por eso mapeamos a MOG-A en stock_data_loader y data_loader"
    },
    "MOG-A": {
        "yahoo": "MOG-A",
        "polygon": "MOG-A",
        "tiingo": "MOG-A",
        "alpha_vantage": "MOG-A",
        "finnhub": "MOG-A",
        "fmp": "MOG-A",
        "twelve_data": "MOG-A",
    },
    "^GSPC": {
        "yahoo": "^GSPC",
        "polygon": "I:SPX",
        "tiingo": "^GSPC",
        "alpha_vantage": None,  # Alpha Vantage no soporta índices con ^
        "finnhub": "^GSPC",     # Finnhub usa ^GSPC
        "fmp": "^GSPC",
        "twelve_data": "SPX",
    },
    "^STOXX50E": {
        "yahoo": "^STOXX50E",
        "polygon": "I:STOXX50E",
        "tiingo": "^STOXX50E",
        "alpha_vantage": None,
        "finnhub": "^STOXX50E",
        "fmp": "^STOXX50E",
        "twelve_data": "STOXX50E",
    },
    "^VIX3M": {
        "yahoo": "^VIX3M",
        "polygon": "I:VIX3M",
        "tiingo": "^VIX3M",
        "alpha_vantage": None,
        "finnhub": "^VIX3M",
        "fmp": "^VIX3M",
        "twelve_data": "VIX3M",
    },
    # === Tickers europeos (mapeo automático) ===
    "AAL.L": {
        "yahoo": "AAL.L",
        "twelve_data": "AAL",
        "alpha_vantage": "AAL.L",
        "tiingo": "AAL.L",
        "finnhub": "AAL.L",
        "fmp": "AAL.L",
        "polygon": "AAL.L",
    },
    "ACS.MC": {
        "yahoo": "ACS.MC",
        "twelve_data": "ACS",
        "alpha_vantage": "ACS.MC",
        "tiingo": "ACS.MC",
        "finnhub": "ACS.MC",
        "fmp": "ACS.MC",
        "polygon": "ACS.MC",
    },
    "ADS.DE": {
        "yahoo": "ADS.DE",
        "twelve_data": "ADS",
        "alpha_vantage": "ADS.DE",
        "tiingo": "ADS.DE",
        "finnhub": "ADS.DE",
        "fmp": "ADS.DE",
        "polygon": "ADS.DE",
    },
    "AENA.MC": {
        "yahoo": "AENA.MC",
        "twelve_data": "AENA",
        "alpha_vantage": "AENA.MC",
        "tiingo": "AENA.MC",
        "finnhub": "AENA.MC",
        "fmp": "AENA.MC",
        "polygon": "AENA.MC",
    },
    "AI.PA": {
        "yahoo": "AI.PA",
        "twelve_data": "AI",
        "alpha_vantage": "AI.PA",
        "tiingo": "AI.PA",
        "finnhub": "AI.PA",
        "fmp": "AI.PA",
        "polygon": "AI.PA",
    },
    "AIR.PA": {
        "yahoo": "AIR.PA",
        "twelve_data": "AIR",
        "alpha_vantage": "AIR.PA",
        "tiingo": "AIR.PA",
        "finnhub": "AIR.PA",
        "fmp": "AIR.PA",
        "polygon": "AIR.PA",
    },
    "ALV.DE": {
        "yahoo": "ALV.DE",
        "twelve_data": "ALV",
        "alpha_vantage": "ALV.DE",
        "tiingo": "ALV.DE",
        "finnhub": "ALV.DE",
        "fmp": "ALV.DE",
        "polygon": "ALV.DE",
    },
    "AMS.MC": {
        "yahoo": "AMS.MC",
        "twelve_data": "AMS",
        "alpha_vantage": "AMS.MC",
        "tiingo": "AMS.MC",
        "finnhub": "AMS.MC",
        "fmp": "AMS.MC",
        "polygon": "AMS.MC",
    },
    "ANA.MC": {
        "yahoo": "ANA.MC",
        "twelve_data": "ANA",
        "alpha_vantage": "ANA.MC",
        "tiingo": "ANA.MC",
        "finnhub": "ANA.MC",
        "fmp": "ANA.MC",
        "polygon": "ANA.MC",
    },
    "ASML.AS": {
        "yahoo": "ASML.AS",
        "twelve_data": "ASML",
        "alpha_vantage": "ASML.AS",
        "tiingo": "ASML.AS",
        "finnhub": "ASML.AS",
        "fmp": "ASML.AS",
        "polygon": "ASML.AS",
    },
    "AZN.L": {
        "yahoo": "AZN.L",
        "twelve_data": "AZN",
        "alpha_vantage": "AZN.L",
        "tiingo": "AZN.L",
        "finnhub": "AZN.L",
        "fmp": "AZN.L",
        "polygon": "AZN.L",
    },
    "BA.L": {
        "yahoo": "BA.L",
        "twelve_data": "BA",
        "alpha_vantage": "BA.L",
        "tiingo": "BA.L",
        "finnhub": "BA.L",
        "fmp": "BA.L",
        "polygon": "BA.L",
    },
    "BARC.L": {
        "yahoo": "BARC.L",
        "twelve_data": "BARC",
        "alpha_vantage": "BARC.L",
        "tiingo": "BARC.L",
        "finnhub": "BARC.L",
        "fmp": "BARC.L",
        "polygon": "BARC.L",
    },
    "BAS.DE": {
        "yahoo": "BAS.DE",
        "twelve_data": "BAS",
        "alpha_vantage": "BAS.DE",
        "tiingo": "BAS.DE",
        "finnhub": "BAS.DE",
        "fmp": "BAS.DE",
        "polygon": "BAS.DE",
    },
    "BATS.L": {
        "yahoo": "BATS.L",
        "twelve_data": "BATS",
        "alpha_vantage": "BATS.L",
        "tiingo": "BATS.L",
        "finnhub": "BATS.L",
        "fmp": "BATS.L",
        "polygon": "BATS.L",
    },
    "BAYN.DE": {
        "yahoo": "BAYN.DE",
        "twelve_data": "BAYN",
        "alpha_vantage": "BAYN.DE",
        "tiingo": "BAYN.DE",
        "finnhub": "BAYN.DE",
        "fmp": "BAYN.DE",
        "polygon": "BAYN.DE",
    },
    "BBVA.MC": {
        "yahoo": "BBVA.MC",
        "twelve_data": "BBVA",
        "alpha_vantage": "BBVA.MC",
        "tiingo": "BBVA.MC",
        "finnhub": "BBVA.MC",
        "fmp": "BBVA.MC",
        "polygon": "BBVA.MC",
    },
    "BKT.MC": {
        "yahoo": "BKT.MC",
        "twelve_data": "BKT",
        "alpha_vantage": "BKT.MC",
        "tiingo": "BKT.MC",
        "finnhub": "BKT.MC",
        "fmp": "BKT.MC",
        "polygon": "BKT.MC",
    },
    "BMW.DE": {
        "yahoo": "BMW.DE",
        "twelve_data": "BMW",
        "alpha_vantage": "BMW.DE",
        "tiingo": "BMW.DE",
        "finnhub": "BMW.DE",
        "fmp": "BMW.DE",
        "polygon": "BMW.DE",
    },
    "BNP.PA": {
        "yahoo": "BNP.PA",
        "twelve_data": "BNP",
        "alpha_vantage": "BNP.PA",
        "tiingo": "BNP.PA",
        "finnhub": "BNP.PA",
        "fmp": "BNP.PA",
        "polygon": "BNP.PA",
    },
    "BP.L": {
        "yahoo": "BP.L",
        "twelve_data": "BP",
        "alpha_vantage": "BP.L",
        "tiingo": "BP.L",
        "finnhub": "BP.L",
        "fmp": "BP.L",
        "polygon": "BP.L",
    },
    "CABK.MC": {
        "yahoo": "CABK.MC",
        "twelve_data": "CABK",
        "alpha_vantage": "CABK.MC",
        "tiingo": "CABK.MC",
        "finnhub": "CABK.MC",
        "fmp": "CABK.MC",
        "polygon": "CABK.MC",
    },
    "CLNX.MC": {
        "yahoo": "CLNX.MC",
        "twelve_data": "CLNX",
        "alpha_vantage": "CLNX.MC",
        "tiingo": "CLNX.MC",
        "finnhub": "CLNX.MC",
        "fmp": "CLNX.MC",
        "polygon": "CLNX.MC",
    },
    "CPG.L": {
        "yahoo": "CPG.L",
        "twelve_data": "CPG",
        "alpha_vantage": "CPG.L",
        "tiingo": "CPG.L",
        "finnhub": "CPG.L",
        "fmp": "CPG.L",
        "polygon": "CPG.L",
    },
    "DB1.DE": {
        "yahoo": "DB1.DE",
        "twelve_data": "DB1",
        "alpha_vantage": "DB1.DE",
        "tiingo": "DB1.DE",
        "finnhub": "DB1.DE",
        "fmp": "DB1.DE",
        "polygon": "DB1.DE",
    },
    "DBK.DE": {
        "yahoo": "DBK.DE",
        "twelve_data": "DBK",
        "alpha_vantage": "DBK.DE",
        "tiingo": "DBK.DE",
        "finnhub": "DBK.DE",
        "fmp": "DBK.DE",
        "polygon": "DBK.DE",
    },
    "DHL.DE": {
        "yahoo": "DHL.DE",
        "twelve_data": "DHL",
        "alpha_vantage": "DHL.DE",
        "tiingo": "DHL.DE",
        "finnhub": "DHL.DE",
        "fmp": "DHL.DE",
        "polygon": "DHL.DE",
    },
    "DTE.DE": {
        "yahoo": "DTE.DE",
        "twelve_data": "DTE",
        "alpha_vantage": "DTE.DE",
        "tiingo": "DTE.DE",
        "finnhub": "DTE.DE",
        "fmp": "DTE.DE",
        "polygon": "DTE.DE",
    },
    "DTG.DE": {
        "yahoo": "DTG.DE",
        "twelve_data": "DTG",
        "alpha_vantage": "DTG.DE",
        "tiingo": "DTG.DE",
        "finnhub": "DTG.DE",
        "fmp": "DTG.DE",
        "polygon": "DTG.DE",
    },
    "ELE.MC": {
        "yahoo": "ELE.MC",
        "twelve_data": "ELE",
        "alpha_vantage": "ELE.MC",
        "tiingo": "ELE.MC",
        "finnhub": "ELE.MC",
        "fmp": "ELE.MC",
        "polygon": "ELE.MC",
    },
    "ENR.DE": {
        "yahoo": "ENR.DE",
        "twelve_data": "ENR",
        "alpha_vantage": "ENR.DE",
        "tiingo": "ENR.DE",
        "finnhub": "ENR.DE",
        "fmp": "ENR.DE",
        "polygon": "ENR.DE",
    },
    "EOAN.DE": {
        "yahoo": "EOAN.DE",
        "twelve_data": "EOAN",
        "alpha_vantage": "EOAN.DE",
        "tiingo": "EOAN.DE",
        "finnhub": "EOAN.DE",
        "fmp": "EOAN.DE",
        "polygon": "EOAN.DE",
    },
    "FER.MC": {
        "yahoo": "FER.MC",
        "twelve_data": "FER",
        "alpha_vantage": "FER.MC",
        "tiingo": "FER.MC",
        "finnhub": "FER.MC",
        "fmp": "FER.MC",
        "polygon": "FER.MC",
    },
    "GLEN.L": {
        "yahoo": "GLEN.L",
        "twelve_data": "GLEN",
        "alpha_vantage": "GLEN.L",
        "tiingo": "GLEN.L",
        "finnhub": "GLEN.L",
        "fmp": "GLEN.L",
        "polygon": "GLEN.L",
    },
    "GSK.L": {
        "yahoo": "GSK.L",
        "twelve_data": "GSK",
        "alpha_vantage": "GSK.L",
        "tiingo": "GSK.L",
        "finnhub": "GSK.L",
        "fmp": "GSK.L",
        "polygon": "GSK.L",
    },
    "HEI.DE": {
        "yahoo": "HEI.DE",
        "twelve_data": "HEI",
        "alpha_vantage": "HEI.DE",
        "tiingo": "HEI.DE",
        "finnhub": "HEI.DE",
        "fmp": "HEI.DE",
        "polygon": "HEI.DE",
    },
    "HSBA.L": {
        "yahoo": "HSBA.L",
        "twelve_data": "HSBA",
        "alpha_vantage": "HSBA.L",
        "tiingo": "HSBA.L",
        "finnhub": "HSBA.L",
        "fmp": "HSBA.L",
        "polygon": "HSBA.L",
    },
    "IAG.MC": {
        "yahoo": "IAG.MC",
        "twelve_data": "IAG",
        "alpha_vantage": "IAG.MC",
        "tiingo": "IAG.MC",
        "finnhub": "IAG.MC",
        "fmp": "IAG.MC",
        "polygon": "IAG.MC",
    },
    "IBE.MC": {
        "yahoo": "IBE.MC",
        "twelve_data": "IBE",
        "alpha_vantage": "IBE.MC",
        "tiingo": "IBE.MC",
        "finnhub": "IBE.MC",
        "fmp": "IBE.MC",
        "polygon": "IBE.MC",
    },
    "IDR.MC": {
        "yahoo": "IDR.MC",
        "twelve_data": "IDR",
        "alpha_vantage": "IDR.MC",
        "tiingo": "IDR.MC",
        "finnhub": "IDR.MC",
        "fmp": "IDR.MC",
        "polygon": "IDR.MC",
    },
    "INGA.AS": {
        "yahoo": "INGA.AS",
        "twelve_data": "INGA",
        "alpha_vantage": "INGA.AS",
        "tiingo": "INGA.AS",
        "finnhub": "INGA.AS",
        "fmp": "INGA.AS",
        "polygon": "INGA.AS",
    },
    "ISP.MI": {
        "yahoo": "ISP.MI",
        "twelve_data": "ISP",
        "alpha_vantage": "ISP.MI",
        "tiingo": "ISP.MI",
        "finnhub": "ISP.MI",
        "fmp": "ISP.MI",
        "polygon": "ISP.MI",
    },
    "ITX.MC": {
        "yahoo": "ITX.MC",
        "twelve_data": "ITX",
        "alpha_vantage": "ITX.MC",
        "tiingo": "ITX.MC",
        "finnhub": "ITX.MC",
        "fmp": "ITX.MC",
        "polygon": "ITX.MC",
    },
    "LLOY.L": {
        "yahoo": "LLOY.L",
        "twelve_data": "LLOY",
        "alpha_vantage": "LLOY.L",
        "tiingo": "LLOY.L",
        "finnhub": "LLOY.L",
        "fmp": "LLOY.L",
        "polygon": "LLOY.L",
    },
    "LSEG.L": {
        "yahoo": "LSEG.L",
        "twelve_data": "LSEG",
        "alpha_vantage": "LSEG.L",
        "tiingo": "LSEG.L",
        "finnhub": "LSEG.L",
        "fmp": "LSEG.L",
        "polygon": "LSEG.L",
    },
    "MBG.DE": {
        "yahoo": "MBG.DE",
        "twelve_data": "MBG",
        "alpha_vantage": "MBG.DE",
        "tiingo": "MBG.DE",
        "finnhub": "MBG.DE",
        "fmp": "MBG.DE",
        "polygon": "MBG.DE",
    },
    "MC.PA": {
        "yahoo": "MC.PA",
        "twelve_data": "MC",
        "alpha_vantage": "MC.PA",
        "tiingo": "MC.PA",
        "finnhub": "MC.PA",
        "fmp": "MC.PA",
        "polygon": "MC.PA",
    },
    "MT.AS": {
        "yahoo": "MT.AS",
        "twelve_data": "MT",
        "alpha_vantage": "MT.AS",
        "tiingo": "MT.AS",
        "finnhub": "MT.AS",
        "fmp": "MT.AS",
        "polygon": "MT.AS",
    },
    "MUV2.DE": {
        "yahoo": "MUV2.DE",
        "twelve_data": "MUV2",
        "alpha_vantage": "MUV2.DE",
        "tiingo": "MUV2.DE",
        "finnhub": "MUV2.DE",
        "fmp": "MUV2.DE",
        "polygon": "MUV2.DE",
    },
    "NG.L": {
        "yahoo": "NG.L",
        "twelve_data": "NG",
        "alpha_vantage": "NG.L",
        "tiingo": "NG.L",
        "finnhub": "NG.L",
        "fmp": "NG.L",
        "polygon": "NG.L",
    },
    "NTGY.MC": {
        "yahoo": "NTGY.MC",
        "twelve_data": "NTGY",
        "alpha_vantage": "NTGY.MC",
        "tiingo": "NTGY.MC",
        "finnhub": "NTGY.MC",
        "fmp": "NTGY.MC",
        "polygon": "NTGY.MC",
    },
    "NWG.L": {
        "yahoo": "NWG.L",
        "twelve_data": "NWG",
        "alpha_vantage": "NWG.L",
        "tiingo": "NWG.L",
        "finnhub": "NWG.L",
        "fmp": "NWG.L",
        "polygon": "NWG.L",
    },
    "OR.PA": {
        "yahoo": "OR.PA",
        "twelve_data": "OR",
        "alpha_vantage": "OR.PA",
        "tiingo": "OR.PA",
        "finnhub": "OR.PA",
        "fmp": "OR.PA",
        "polygon": "OR.PA",
    },
    "REL.L": {
        "yahoo": "REL.L",
        "twelve_data": "REL",
        "alpha_vantage": "REL.L",
        "tiingo": "REL.L",
        "finnhub": "REL.L",
        "fmp": "REL.L",
        "polygon": "REL.L",
    },
    "REP.MC": {
        "yahoo": "REP.MC",
        "twelve_data": "REP",
        "alpha_vantage": "REP.MC",
        "tiingo": "REP.MC",
        "finnhub": "REP.MC",
        "fmp": "REP.MC",
        "polygon": "REP.MC",
    },
    "RHM.DE": {
        "yahoo": "RHM.DE",
        "twelve_data": "RHM",
        "alpha_vantage": "RHM.DE",
        "tiingo": "RHM.DE",
        "finnhub": "RHM.DE",
        "fmp": "RHM.DE",
        "polygon": "RHM.DE",
    },
    "RIO.L": {
        "yahoo": "RIO.L",
        "twelve_data": "RIO",
        "alpha_vantage": "RIO.L",
        "tiingo": "RIO.L",
        "finnhub": "RIO.L",
        "fmp": "RIO.L",
        "polygon": "RIO.L",
    },
    "RR.L": {
        "yahoo": "RR.L",
        "twelve_data": "RR",
        "alpha_vantage": "RR.L",
        "tiingo": "RR.L",
        "finnhub": "RR.L",
        "fmp": "RR.L",
        "polygon": "RR.L",
    },
    "RWE.DE": {
        "yahoo": "RWE.DE",
        "twelve_data": "RWE",
        "alpha_vantage": "RWE.DE",
        "tiingo": "RWE.DE",
        "finnhub": "RWE.DE",
        "fmp": "RWE.DE",
        "polygon": "RWE.DE",
    },
    "SAB.MC": {
        "yahoo": "SAB.MC",
        "twelve_data": "SAB",
        "alpha_vantage": "SAB.MC",
        "tiingo": "SAB.MC",
        "finnhub": "SAB.MC",
        "fmp": "SAB.MC",
        "polygon": "SAB.MC",
    },
    "SAF.PA": {
        "yahoo": "SAF.PA",
        "twelve_data": "SAF",
        "alpha_vantage": "SAF.PA",
        "tiingo": "SAF.PA",
        "finnhub": "SAF.PA",
        "fmp": "SAF.PA",
        "polygon": "SAF.PA",
    },
    "SAN.MC": {
        "yahoo": "SAN.MC",
        "twelve_data": "SAN",
        "alpha_vantage": "SAN.MC",
        "tiingo": "SAN.MC",
        "finnhub": "SAN.MC",
        "fmp": "SAN.MC",
        "polygon": "SAN.MC",
    },
    "SAP.DE": {
        "yahoo": "SAP.DE",
        "twelve_data": "SAP",
        "alpha_vantage": "SAP.DE",
        "tiingo": "SAP.DE",
        "finnhub": "SAP.DE",
        "fmp": "SAP.DE",
        "polygon": "SAP.DE",
    },
    "SHEL.L": {
        "yahoo": "SHEL.L",
        "twelve_data": "SHEL",
        "alpha_vantage": "SHEL.L",
        "tiingo": "SHEL.L",
        "finnhub": "SHEL.L",
        "fmp": "SHEL.L",
        "polygon": "SHEL.L",
    },
    "SIE.DE": {
        "yahoo": "SIE.DE",
        "twelve_data": "SIE",
        "alpha_vantage": "SIE.DE",
        "tiingo": "SIE.DE",
        "finnhub": "SIE.DE",
        "fmp": "SIE.DE",
        "polygon": "SIE.DE",
    },
    "STAN.L": {
        "yahoo": "STAN.L",
        "twelve_data": "STAN",
        "alpha_vantage": "STAN.L",
        "tiingo": "STAN.L",
        "finnhub": "STAN.L",
        "fmp": "STAN.L",
        "polygon": "STAN.L",
    },
    "SU.PA": {
        "yahoo": "SU.PA",
        "twelve_data": "SU",
        "alpha_vantage": "SU.PA",
        "tiingo": "SU.PA",
        "finnhub": "SU.PA",
        "fmp": "SU.PA",
        "polygon": "SU.PA",
    },
    "TEF.MC": {
        "yahoo": "TEF.MC",
        "twelve_data": "TEF",
        "alpha_vantage": "TEF.MC",
        "tiingo": "TEF.MC",
        "finnhub": "TEF.MC",
        "fmp": "TEF.MC",
        "polygon": "TEF.MC",
    },
    "TTE.PA": {
        "yahoo": "TTE.PA",
        "twelve_data": "TTE",
        "alpha_vantage": "TTE.PA",
        "tiingo": "TTE.PA",
        "finnhub": "TTE.PA",
        "fmp": "TTE.PA",
        "polygon": "TTE.PA",
    },
    "UCG.MI": {
        "yahoo": "UCG.MI",
        "twelve_data": "UCG",
        "alpha_vantage": "UCG.MI",
        "tiingo": "UCG.MI",
        "finnhub": "UCG.MI",
        "fmp": "UCG.MI",
        "polygon": "UCG.MI",
    },
    "ULVR.L": {
        "yahoo": "ULVR.L",
        "twelve_data": "ULVR",
        "alpha_vantage": "ULVR.L",
        "tiingo": "ULVR.L",
        "finnhub": "ULVR.L",
        "fmp": "ULVR.L",
        "polygon": "ULVR.L",
    },
}

def resolve_symbol(canonical_ticker: str, provider: str):
    """Devuelve el símbolo específico del proveedor para un ticker canónico.
    Si no hay mapeo especial, asume que el ticker es el mismo y lo devuelve sin cambios.
    """
    inst = INSTRUMENTS.get(canonical_ticker)
    if inst:
        symbol = inst.get(provider)
        if symbol is None:
            # Proveedor no soporta el instrumento
            return None
        return symbol
    # Si no está en el registro, asumir que el ticker es directo (acciones USA, ETFs, etc.)
    return canonical_ticker

def is_supported(canonical_ticker: str, provider: str) -> bool:
    """Indica si un proveedor puede proporcionar datos para el ticker canónico."""
    inst = INSTRUMENTS.get(canonical_ticker)
    if inst:
        return inst.get(provider) is not None
    # Para tickers no mapeados, asumimos soporte (puede fallar pero no lo sabremos)
    return True
